name: 🚀 Auto Cool Level Generator

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  generate-level:
    name: 🌟 Generate Cool Level
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: ✨ Gaming Level Unlocked Banner
        run: |
          echo ""
          echo "╔═══🗃️══════════🗃️═══╗"
          echo "      🗂️DATABASE MIGRATED🗂️  "
          echo " 🔒SECURITY PATCH APPLIED🔒 "
          echo "   💾BACKUPS COMPLETED💾  "
          echo "╚═══🗃️══════════🗃️═══╝"
          echo ""

      - name: 📝 Generate Next Cool Level (no ASCII)
        shell: bash
        run: |
          set -e

          cool_names=(
            "Vortex" "Nebula" "Phoenix" "Falcon" "Titan" "Shadow" "Blaze" "Nova" "Specter" "Stellar"
            "Inferno" "Cosmos" "Zephyr" "Obsidian" "Glacier" "Thunder" "Matrix" "Aurora" "Samurai" "Ninja"
            "Ronin" "Valkyrie" "Oracle" "Sonic" "Ranger" "Drift" "Mirage" "Cipher" "Echo" "Titanium"
            "Genesis" "Saber" "Onyx" "Blizzard" "Venom" "Storm" "Astro" "Galaxy" "Eclipse" "Magma"
            "Turbo" "Rogue" "Elemental" "Surge" "Radiant" "Zenith" "Prime" "Sentinel" "Golem" "Mystic"
          )

          programmer_quotes=(
            "“Talk is cheap. Show me the code.” – Linus Torvalds"
            "“Programs must be written for people to read, and only incidentally for machines to execute.” – Harold Abelson"
            "“First, solve the problem. Then, write the code.” – John Johnson"
            "“Simplicity is the soul of efficiency.” – Austin Freeman"
            "“Code is like humor. When you have to explain it, it’s bad.” – Cory House"
            "“Experience is the name everyone gives to their mistakes.” – Oscar Wilde"
            "“Fix the cause, not the symptom.” – Steve Maguire"
            "“Before software can be reusable it first has to be usable.” – Ralph Johnson"
            "“Make it work, make it right, make it fast.” – Kent Beck"
            "“The best error message is the one that never shows up.” – Thomas Fuchs"
          )

          RANDOM_QUOTE="${programmer_quotes[$RANDOM % ${#programmer_quotes[@]}]}"
          echo "PROGRAMMER_QUOTE=$RANDOM_QUOTE" >> $GITHUB_ENV

          mkdir -p levels

          last_name=""
          if ls levels/level-*-*.txt 1> /dev/null 2>&1; then
            last_file=$(ls levels/level-*-*.txt | sort | tail -n 1)
            last_name=$(basename "$last_file" | sed -E 's/level-[0-9]{8}-[0-9]{4}-(.*)\.txt/\1/')
          fi

          idx=0
          if [ -n "$last_name" ]; then
            for i in "${!cool_names[@]}"; do
              if [[ "${cool_names[$i]}" == "$last_name" ]]; then
                idx=$(( (i + 1) % ${#cool_names[@]} ))
                break
              fi
            done
          fi

          next_name="${cool_names[$idx]}"
          file_name="levels/level-$(date +%Y%m%d-%H%M)-${next_name}.txt"

          {
            echo "# 🌌 Level: $next_name"
            echo "# Generated at: $(date -u)"
            echo "# By: winfredween@gmail.com"
          } > "$file_name"

          echo "LEVEL_NAME=$next_name" >> $GITHUB_ENV
          echo "Created $file_name"

      - name: ⏰ Generate Formatted Time
        run: |
          echo "FORMATTED_TIME=$(TZ='Asia/Jakarta' date '+%d/%m/%Y %H:%M:%S WIB')" >> $GITHUB_ENV

      - name: 🔢 Generate Notification Counter
        id: notif-counter
        run: |
          count=$(ls levels/level-*-*.txt 2>/dev/null | wc -l)
          echo "NOTIF_COUNTER=$count" >> $GITHUB_ENV

      - name: 🔔 Send Notification to Telegram
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>╔═══🗃️══════════🗃️═══╗</b>
            <b>     🗂️<b>DATABASE MIGRATED</b>🗂️  </b>
            <b> 🔒<b>SECURITY PATCH APPLIED</b>🔒 </b>
            <b>    💾BACKUPS COMPLETED💾  </b>
            <b>╚═══🗃️══════════🗃️═══╝</b>

            <b>• 🧩 Feature ID :</b> <b>${{ env.LEVEL_NAME }}</b>
            <b>• 🌐 Git Repo :</b> <b>${{ github.repository }}</b>
            <b>• ⏳ Deployed At :</b> <b>${{ env.FORMATTED_TIME }}</b>
            <b>• 🧾 CI Run # :</b> <b>${{ env.NOTIF_COUNTER }}</b>
            <b>• 🔐 Commit Auth :</b> <b>winfredween@gmail.com</b>

            <b>#DeployLikeAPro #DevOpsMode</b>
            <b>💯 This script was 100% created by Abie Haryatmo</b>
            <i>${{ env.PROGRAMMER_QUOTE }}</i>
          format: html

      - name: 🤖 Configure Git
        run: |
          git config user.name "winfredween"
          git config user.email "winfredween@gmail.com"

      - name: 🚩 Commit & Push Changes
        run: |
          git add levels/
          git commit -m "✨ Add Level: ${{ env.LEVEL_NAME }} (by winfredween@gmail.com)" || echo "Nothing to commit"
          git push
